name: health_example
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 4.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health:
    path: ../

flutter:
  uses-material-design: true
